### ISSUE TITLE
`rent_time` should be empty instead of 'week' in the database, for the books which have not been added for renting!

### ISSUE THREAD

**Issue by 526avijitgupta** [yashmehrotra/BookAway#65]
Here is the screenshot of the same
(Take a close look at the `rent_time` attribute, and you will comprehend what is the problem)
![Database: `bfb` => table: `tbl_books`](https://cloud.githubusercontent.com/assets/7583815/5694849/3da111ba-99a3-11e4-9eef-5981d408b187.png)

**Comment by yashmehrotra** [comment]
Solved @526avijitgupta  in your face
