### ISSUE TITLE
Home page revamping

### ISSUE THREAD

**Issue by 526avijitgupta** [yashmehrotra/BookAway#71]
Home page should be revamped as to contain the following items at least:
1. A background image, with some content written over it.
2. Scrolling down to some nice svg's/graphics as to the consumer benefits of bookaway.
3. Contact us and about us should be accomodated on the homepage itself.

An example: http://sandbox.decision-box.com/

**Comment by yashmehrotra** [comment]
@526avijitgupta What's your progress on this ?
